### ISSUE TITLE
moviepy broken dependency

### ISSUE THREAD

**Issue by henrieger** [FolhaSP/mosaico#20]
Hi, I was getting the following error while running the library:

```
ModuleNotFoundError: No module named 'moviepy.video.fx.resize'
```

This import can be found on `effects/pan.py` and `effects/zoom.py`.

Uppon further investigation, I discovered that the library only requires moviepy versions greater that 2.0.0.dev2, and pip installed version 2.1.1 for me. I assume 2.0.0.dev2 was used during development, but since then breaking changes to the library caused incompatibilities with more recent versions.

As 2.0.0.dev2 was a pre-release development version, I suggest you change the requirement to the stable version 2.0.0 and fix the required imports where needed (for example, since 2.0.0 `resize.py` got renamed to `Resize.py`).

**Comment by leodiegues** [comment]
Moviepy updated this November 20th after 4 years without releases. Meanwhile, I will lock the moviepy version to 2.0.0-dev so we can work on any breaking changes.
