### ISSUE TITLE
Essencial libraries missing on fresh install

### ISSUE THREAD

**Issue by henrieger** [FolhaSP/mosaico#21]
Hi,
I had an issue trying to run a script with mosaico as libraries `instructor`, `litellm`, `assemblyai` and `elevenlabs` were not installed by default on running `pip install mosaico` and had to be installed manually. I read the `METADATA` file for the package and these libraries are present, but for some reason were not installed. Could you please investigate that? 
Thanks in advance.

**Comment by leodiegues** [comment]
Again, this is a problem of poor documentation. You can install those packages by executing `pip install "mosaico[news]"`. Will also fix this in the docs.

Sorry about the inconveniences and thanks for the feedback!
